# Generated by Django 2.1.4 on 2019-02-02 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('street_address', models.CharField(max_length=50, null=True, verbose_name='Street address')),
                ('unit', models.CharField(max_length=5, null=True, verbose_name='Unit #')),
                ('city', models.CharField(max_length=60, verbose_name='City')),
                ('state_province', models.CharField(max_length=50, null=True, verbose_name='State / Province')),
                ('zip_code', models.CharField(max_length=12, null=True, verbose_name='ZIP / Postal code')),
                ('country', models.CharField(max_length=50, null=True, verbose_name='Country')),
                ('furnace_temperature', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Furnace Temperature')),
                ('furnace_status', models.CharField(blank=True, choices=[('OFF', 'OFF'), ('FAN', 'Running Fan'), ('HEAT', 'Running Heat')], default='OFF', max_length=15, null=True, verbose_name='Furnace Status')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('room_label', models.CharField(max_length=50, null=True, verbose_name='Room Label')),
                ('room_temperature', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Room Temperature')),
                ('light_status', models.CharField(blank=True, choices=[('ON', 'ON'), ('OFF', 'OFF'), ('NL', 'No Lights')], default='OFF', max_length=4, null=True, verbose_name='Light Status')),
                ('house', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hauto.House')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('room_label', 'house')},
        ),
    ]
